### ISSUE TITLE
Documentar o projeto

### ISSUE THREAD

**Issue by henriquecf** [osmarpixuri/integracao201701#12]
@rodolphohiroshi como você tinha falado que ia pegar essa. Caso tenha alguma dúvida podemos nos falar por aqui. Eu mesmo não tenho muito certeza do que deve ser feito aqui...

**Comment by rodolphohiroshi** [comment]
@henriquecf beleza, inicialmente, vou adicionar os documentos padrões de um projeto, tap, eor e o documento do gerenciamento de projeto, nele vamos especificar as dificuldades e evolução do trabalho
